name: Update MoeCounter

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get binary count
        id: get-listc
        run: |
          LISTC=$(wget -qO- "https://raw.githubusercontent.com/xplshn/bigdl/master/stubdl" | sh -s -- list | wc -l)
          echo "LISTC=$LISTC" >> $GITHUB_ENV
      
      - name: Download MoeCounter image
        run: |
          LISTC=$LISTC
          wget -O .assets/counter.gif "https://api.sefinek.net/api/v2/moecounter?number=${LISTC}&length=10&theme=gelbooru&pixelated=true"
      
      - name: Upload MoeCounter image artifact
        uses: actions/upload-artifact@v4
        with:
          name: moecounter-image
          path: .assets/counter.gif
